version: "2"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: nodemon -L --exec "npm start" --watch src  
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/build
    ports:
      - "3000:3000"
      - "9229:9229"
    environment:
      - ENVIRONMENT
      - NODE_ENV
